### ISSUE TITLE
Notice: Undefined property: stdClass::$compile_option

### ISSUE THREAD

**Issue by parasew** [enricodeleo/wpacked#5]
There is an error thrown, which seems to be a known error in wp-sqlite-integration
`Notice: Undefined property: stdClass::$compile_option in .../plugins/sqlite-integration`

https://github.com/aaemnnosttv/wp-sqlite-integration/issues/1

the only solution to this for now is to add these two files to .env

WP_DEBUG='false'
WP_DEBUG_LOG='false'

**Comment by enricodeleo** [comment]
Hi @parasew closing this issue cause the error is no reproducible with latest codebase
